name: $(date:yyyy.M.d)$(rev:.r)
trigger:
  batch: 'true'
  branches:
    include:
    - main
  paths:
    include: 
    - '/Azure/Arm&Bicep/*'
    exclude:
    - '/.vscode/*'
    - '/*.md'

resources:
  repositories:
  - repository: yamlTemplates
    type: github
    endpoint: ArnoPeters
    name: "ArnoPeters/Starterkit_AzureDevops"

pool:
  vmImage: 'ubuntu-latest'
  
variables:
- group: 'Azure Release - Global values' # Contains the values for uploading to Azure

stages:
- stage: Build
  jobs:
  - template: yaml/jobs/Azure/publishTemplateSpecs.yml@yamlTemplates
    parameters:
      templateFolder: "Azure/Arm&Bicep"
      resourceGroupName: "aps-deployment-rg"
      resoureGrouplocation: $(defaultAzureResourceLocation)
      azureServiceConnectionName: $(azureServiceConnectionName)
